#
# Generated by dumpDCWorkflow.py written by Sebastien Bigaret
# Original workflow id/title: OIEStudentApplicationWorkflow/OIEStudentApplicationWorkflow
# Date: 2008/05/28 15:48:39.623 GMT-5
#
# WARNING: this dumps does NOT contain any scripts you might have added to
# the workflow, IT IS YOUR RESPONSABILITY TO MAKE BACKUPS FOR THESE SCRIPTS.
#
# The following scripts have been detected and should be backed up:
# - pre_declineFromFacultyReview (External Method)
# - pre_manageDeadlines (External Method)
# - pre_holdForFAIncomplete (External Method)
# - pre_archive (External Method)
# - pre_withdraw (External Method)
# - pre_addToWaitlist (External Method)
# - pre_assignSeat (External Method)
# - post_archive (External Method)
# - post_sendForDirectorReview (External Method)
# - pre_sendForFacultyReview (External Method)
# - post_addToWaitlist (External Method)
# - post_decline (External Method)
# - post_assertReadyForConditionalAdmit (External Method)
# - pre_sendForProgramManagerReview (External Method)
# - pre_waitForPrintedMaterials (External Method)
# - pre_admitConditionally (External Method)
# - pre_sendForDirectorReview (External Method)
# - post_manageDeadlines (External Method)
# - post_sendForProgramManagerReview (External Method)
# - post_submit (External Method)
# - post_waitForPrintedMaterials (External Method)
# - pre_submit (External Method)
# - post_withdraw (External Method)
# - pre_decline (External Method)
# - pre_addComment (External Method)
# - post_sendForFacultyReview (External Method)
# - post_declineFromFacultyReview (External Method)
# - post_assignSeat (External Method)
# - post_recheckForFAHold (External Method)
# - post_holdForFAIncomplete (External Method)
# - post_addComment (External Method)
# - pre_facultyApproves (External Method)
# - pre_approveForFA (External Method)
# - post_admitConditionally (External Method)
# - attempt_transition_to_FAHeld (External Method)
# - pre_assertReadyForConditionalAdmit (External Method)
# - post_approveForFA (External Method)
# - pre_recheckForFAHold (External Method)
# - post_facultyApproves (External Method)
#
"""
Programmatically create a workflow type.
"""
__version__ = "$Id: dumpDCWorkflow.py 25723 2006-07-04 08:41:22Z b_mathieu $"

from Products.CMFCore.WorkflowTool import addWorkflowFactory
from Products.DCWorkflow.DCWorkflow import DCWorkflowDefinition
from Products.PythonScripts.PythonScript import PythonScript
from Products.ExternalMethod.ExternalMethod import ExternalMethod

def setup_OIEStudentApplicationWorkflow(wf):
    """Setup the workflow
    """
    wf.setProperties(title='OIEStudentApplicationWorkflow')

    for s in ('FAHeldIncomplete',
              'archived',
              'conditionallyAdmitted',
              'deadlineManagement',
              'declined',
              'facApprovedNeedsProgramManagerReview',
              'facultyReview',
              'incomplete',
              'needsDirectorReview',
              'needsProgramManagerReview',
              'private',
              'readyForConditionalAdmit',
              'seatAssigned',
              'waitingForPrintMaterials',
              'waitlist',
              'withdrawn'):
        wf.states.addState(s)
    for t in ('addComment',
              'addToWaitlist',
              'admitConditionally',
              'approveForFA',
              'archive',
              'assertReadyForConditionalAdmit',
              'assignSeat',
              'decline',
              'declineFromFacultyReview',
              'facultyApproves',
              'holdForFAIncomplete',
              'manageDeadlines',
              'recheckForFAHold',
              'sendForDirectorReview',
              'sendForFacultyReview',
              'sendForProgramManagerReview',
              'submit',
              'waitForPrintedMaterials',
              'withdraw'):
        wf.transitions.addTransition(t)
    for v in ('action', 'actor', 'comments', 'review_history', 'time'):
        wf.variables.addVariable(v)
    for l in ('uwosh_oie_worklist_archived',
              'uwosh_oie_worklist_conditionallyadmitted',
              'uwosh_oie_worklist_deadlinemanagement',
              'uwosh_oie_worklist_declined',
              'uwosh_oie_worklist_facapprovedneedsprogrammanagerreview',
              'uwosh_oie_worklist_facultyreview',
              'uwosh_oie_worklist_faheldincomplete',
              'uwosh_oie_worklist_incomplete',
              'uwosh_oie_worklist_needsdirectorreview',
              'uwosh_oie_worklist_needsprogrammanagerreview',
              'uwosh_oie_worklist_private',
              'uwosh_oie_worklist_readyforconditionaladmit',
              'uwosh_oie_worklist_seatassigned',
              'uwosh_oie_worklist_waitingforprintmaterials',
              'uwosh_oie_worklist_waitlist',
              'uwosh_oie_worklist_withdrawn'):
        wf.worklists.addWorklist(l)
    for p in ('list',
              'Modify portal content',
              'View',
              'Access contents information',
              'UWOshOIE: Review OIE Application',
              'UWOshOIE: Modify revisable fields',
              'UWOshOIE: Modify Financial Aid fields',
              'UWOshOIE: Modify Office Use Only fields',
              'UWOshOIE: Modify normal fields',
              'Undo changes',
              'List undoable changes'):
        wf.addManagedPermission(p)

    # Initial State
    wf.states.setInitialState('private')

    # State Initialization
    sdef = wf.states['FAHeldIncomplete']
    sdef.setProperties(title='Financial Aid Held Incomplete',
                       description='You will only study abroad if financial aid is available; you do not have a seat on this study abroad program.  This application can not be processed further until you release your Financial Aid HOLD.',
                       transitions=('addComment', 'approveForFA', 'decline', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEFinAid', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['archived']
    sdef.setProperties(title='Archived',
                       description='Archived applications are stored indefinitely and cannot be altered.',
                       transitions=('addComment',))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       [])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       [])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['conditionallyAdmitted']
    sdef.setProperties(title='Conditionally Admitted',
                       description='You have been conditionally admitted but you do not yet have a seat on a study abroad program.  ----- For most programs, seats are assigned in the order in which qualified applicants have completed their applications to this point PROVIDED the applicant ALSO completes all remaining requirements by the Friday following the application deadline. Therefore, applicants on the waiting list may receive seats if applicants who have been conditionally admitted have not completed all requirements. ----- For competitive programs, seats are assigned to the most qualified applicants provided STEP III has also been completed by the Friday following the application deadline.',
                       transitions=('addComment', 'decline', 'manageDeadlines', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['deadlineManagement']
    sdef.setProperties(title='Deadline Management',
                       description='You have been conditionally admitted but you do not yet have a seat on a study abroad program. ----- For most programs, seats are assigned in the order in which qualified applicants have completed their applications to this point PROVIDED the applicant ALSO completes all remaining requirements by the Friday following the application deadline. Therefore, applicants on the waiting list may receive seats if applicants who have been conditionally admitted have not completed all requirements. ----- For competetive programs, seats are assigned to the most qualified applicants provided STEP III has also been completed by the Friday following the application deadline.',
                       transitions=('addComment', 'assignSeat', 'decline', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEFacReview', 'UWOshOIEFrontLineAdvisor'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['declined']
    sdef.setProperties(title='Declined',
                       description='The study abroad application has been declined.',
                       transitions=('addComment', 'archive'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       [])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       [])
    sdef.setPermission('Undo changes', 1,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 1,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['facApprovedNeedsProgramManagerReview']
    sdef.setProperties(title='Faculty Approved and Now Needs Program Manager Review',
                       description='The faculty reviewer has reviewed this application.  Your application is pending further review by the OIE Program Manager; you do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'addToWaitlist', 'assertReadyForConditionalAdmit', 'decline', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['facultyReview']
    sdef.setProperties(title='Faculty Review',
                       description='Your application is pending faculty review; you do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'declineFromFacultyReview', 'facultyApproves', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEFacReview'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['incomplete']
    sdef.setProperties(title='Incomplete',
                       description='You have completed part of the application process but must submit additional materials to the Office of International Education.  This application cannot be processed further until these materials have been submitted; you do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'decline', 'holdForFAIncomplete', 'recheckForFAHold', 'waitForPrintedMaterials', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEFrontLineAdvisor'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['needsDirectorReview']
    sdef.setProperties(title='Needs Director Review',
                       description='Your application is pending review by the OIE Director; you do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'decline', 'sendForProgramManagerReview', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEDirector'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['needsProgramManagerReview']
    sdef.setProperties(title='Needs Program Manager Review',
                       description='Your application is pending review by the OIE Program Manager; you do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'addToWaitlist', 'assertReadyForConditionalAdmit', 'decline', 'sendForFacultyReview', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['private']
    sdef.setProperties(title='Private',
                       description='The Office of International Education does not currently have access to your application.  You MUST submit your application using the purple "SUBMIT APP" button below.',
                       transitions=('addComment', 'submit', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner'])
    sdef.setPermission('View', 0,
                       ['Owner'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['Owner'])
    sdef.setPermission('Undo changes', 1,
                       [])
    sdef.setPermission('List undoable changes', 1,
                       [])

    sdef = wf.states['readyForConditionalAdmit']
    sdef.setProperties(title='Ready For Conditionally Admit',
                       description='The OIE is sorting applications by completion date & time in order to determine conditional admission.  You do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'admitConditionally', 'decline', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['seatAssigned']
    sdef.setProperties(title='Seat Assigned',
                       description='The application process is complete and a seat has been assigned on a study abroad program. Welcome to the program!',
                       transitions=('addComment', 'archive', 'decline', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEFrontLineAdvisor'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['waitingForPrintMaterials']
    sdef.setProperties(title='Waiting For Printed Materials',
                       description='You have completed part of the application process but must submit additional materials to the Office of International Education.  This application cannot be processed further until these materials have been submitted; you do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'decline', 'sendForDirectorReview', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEFrontLineAdvisor'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['waitlist']
    sdef.setProperties(title='Waitlist',
                       description='You are on the waiting list.  You do not yet have a seat on this study abroad program.',
                       transitions=('addComment', 'assertReadyForConditionalAdmit', 'decline', 'withdraw'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       ['UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       ['UWOshOIEDirector',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    sdef = wf.states['withdrawn']
    sdef.setProperties(title='Withdrawn',
                       description='You have withdrawn your on-line study abroad application only.  You must officially withdraw from the study abroad program by contacting the OIE IN WRITING.  See your email in-box for details.',
                       transitions=('addComment', 'archive'))
    sdef.setPermission('list', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                       [])
    sdef.setPermission('View', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                       ['Owner',
                       'UWOshOIEDirector',
                       'UWOshOIEFacReview',
                       'UWOshOIEFinAid',
                       'UWOshOIEFrontLineAdvisor',
                       'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Review OIE Application', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify revisable fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Financial Aid fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                       [])
    sdef.setPermission('UWOshOIE: Modify normal fields', 0,
                       [])
    sdef.setPermission('Undo changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])
    sdef.setPermission('List undoable changes', 0,
                       ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    # Transition Initialization
    tdef = wf.transitions['addComment']
    tdef.setProperties(title='Add a Comment',
                       description='Add Comment',
                       new_state_id='',
                       trigger_type=1,
                       script_name='pre_addComment',
                       after_script_name='post_addComment',
                       actbox_name='addComment',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'Owner; UWOshOIEFinAid; UWOshOIEExtReview; UWOshOIEFacReview; UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEDirector'},
                       )

    tdef = wf.transitions['addToWaitlist']
    tdef.setProperties(title='Add this Student to the Waitlist',
                       description='Add To Waitlist',
                       new_state_id='waitlist',
                       trigger_type=1,
                       script_name='pre_addToWaitlist',
                       after_script_name='post_addToWaitlist',
                       actbox_name='addToWaitlist',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEProgramManager'},
                       )

    tdef = wf.transitions['admitConditionally']
    tdef.setProperties(title='Admit this Student Conditionally',
                       description='Admit Conditionally',
                       new_state_id='conditionallyAdmitted',
                       trigger_type=1,
                       script_name='pre_admitConditionally',
                       after_script_name='post_admitConditionally',
                       actbox_name='admitConditionally',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEProgramManager'},
                       )

    tdef = wf.transitions['approveForFA']
    tdef.setProperties(title='Approve for Financial Aid',
                       description='Approve For Fin Aid',
                       new_state_id='waitingForPrintMaterials',
                       trigger_type=1,
                       script_name='pre_approveForFA',
                       after_script_name='post_approveForFA',
                       actbox_name='approveForFA',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEFinAid'},
                       )

    tdef = wf.transitions['archive']
    tdef.setProperties(title='Archive the Application',
                       description='Archive App',
                       new_state_id='archived',
                       trigger_type=1,
                       script_name='pre_archive',
                       after_script_name='post_archive',
                       actbox_name='archive',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEDirector'},
                       )

    tdef = wf.transitions['assertReadyForConditionalAdmit']
    tdef.setProperties(title='Assert Applicant Is Ready to be Conditionally Admitted',
                       description='Assert App For Con. Admit',
                       new_state_id='readyForConditionalAdmit',
                       trigger_type=1,
                       script_name='pre_assertReadyForConditionalAdmit',
                       after_script_name='post_assertReadyForConditionalAdmit',
                       actbox_name='assertReadyForConditionalAdmit',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEProgramManager'},
                       )

    tdef = wf.transitions['assignSeat']
    tdef.setProperties(title='Assign a Seat to the Applicant and Complete the Application.',
                       description='Assign Seat',
                       new_state_id='seatAssigned',
                       trigger_type=1,
                       script_name='pre_assignSeat',
                       after_script_name='post_assignSeat',
                       actbox_name='assignSeat',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor'},
                       )

    tdef = wf.transitions['decline']
    tdef.setProperties(title='Decline This Application',
                       description='Decline',
                       new_state_id='declined',
                       trigger_type=1,
                       script_name='pre_decline',
                       after_script_name='post_decline',
                       actbox_name='decline',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEDirector'},
                       )

    tdef = wf.transitions['declineFromFacultyReview']
    tdef.setProperties(title='Decline This Application From Faculty Review',
                       description='Faculty Decline',
                       new_state_id='declined',
                       trigger_type=1,
                       script_name='pre_declineFromFacultyReview',
                       after_script_name='post_declineFromFacultyReview',
                       actbox_name='declinedFromFacultyReview',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFacReview; UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEDirector'},
                       )

    tdef = wf.transitions['facultyApproves']
    tdef.setProperties(title='Approve This Application From Faculty Review',
                       description='Faculty Approve',
                       new_state_id='facApprovedNeedsProgramManagerReview',
                       trigger_type=1,
                       script_name='pre_facultyApproves',
                       after_script_name='post_facultyApproves',
                       actbox_name='facultyApproves',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFacReview; UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEDirector'},
                       )

    tdef = wf.transitions['holdForFAIncomplete']
    tdef.setProperties(title='Hold For Financial Aid - incomplete',
                       description='Hold For Fin Aid',
                       new_state_id='FAHeldIncomplete',
                       trigger_type=1,
                       script_name='pre_holdForFAIncomplete',
                       after_script_name='post_holdForFAIncomplete',
                       actbox_name='holdForFAIncomplete',
                       actbox_url='',
                       actbox_category='workflow',
                       props=None,
                       )

    tdef = wf.transitions['manageDeadlines']
    tdef.setProperties(title='Begin Managing Deadlines For This Application',
                       description='Manage Deadlines',
                       new_state_id='deadlineManagement',
                       trigger_type=1,
                       script_name='pre_manageDeadlines',
                       after_script_name='post_manageDeadlines',
                       actbox_name='manageDeadlines',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor; UWOshOIEProgramManager; UWOshOIEDirector'},
                       )

    tdef = wf.transitions['recheckForFAHold']
    tdef.setProperties(title='Check If HOLD Has Been Set for Financial Aid',
                       description='Recheck For FA Hold',
                       new_state_id='incomplete',
                       trigger_type=1,
                       script_name='pre_recheckForFAHold',
                       after_script_name='post_recheckForFAHold',
                       actbox_name='recheckForFAHold',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor'},
                       )

    tdef = wf.transitions['sendForDirectorReview']
    tdef.setProperties(title='Send to OIE Director For Review',
                       description='Send For Director Rev',
                       new_state_id='needsDirectorReview',
                       trigger_type=1,
                       script_name='pre_sendForDirectorReview',
                       after_script_name='post_sendForDirectorReview',
                       actbox_name='sendForDirectorReview',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor'},
                       )

    tdef = wf.transitions['sendForFacultyReview']
    tdef.setProperties(title='Send to Faculty For Review',
                       description='Send For Fac Rev',
                       new_state_id='facultyReview',
                       trigger_type=1,
                       script_name='pre_sendForFacultyReview',
                       after_script_name='post_sendForFacultyReview',
                       actbox_name='sendForFacultyReview',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEProgramManager'},
                       )

    tdef = wf.transitions['sendForProgramManagerReview']
    tdef.setProperties(title='Send To OIE Program Manager For Review',
                       description='Send For Pgm Mgr Rev',
                       new_state_id='needsProgramManagerReview',
                       trigger_type=1,
                       script_name='pre_sendForProgramManagerReview',
                       after_script_name='post_sendForProgramManagerReview',
                       actbox_name='sendForProgramManagerReview',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEDirector'},
                       )

    tdef = wf.transitions['submit']
    tdef.setProperties(title='Submit Application To OIE',
                       description='Submit App',
                       new_state_id='incomplete',
                       trigger_type=1,
                       script_name='pre_submit',
                       after_script_name='post_submit',
                       actbox_name='submit',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'Owner'},
                       )

    tdef = wf.transitions['waitForPrintedMaterials']
    tdef.setProperties(title='Wait For Printed Materials From Student',
                       description='Wait For Printed Materials',
                       new_state_id='waitingForPrintMaterials',
                       trigger_type=1,
                       script_name='pre_waitForPrintedMaterials',
                       after_script_name='post_waitForPrintedMaterials',
                       actbox_name='waitForPrintedMaterials',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'UWOshOIEFrontLineAdvisor'},
                       )

    tdef = wf.transitions['withdraw']
    tdef.setProperties(title='Withdraw This Application From Consideration',
                       description='Withdraw App',
                       new_state_id='withdrawn',
                       trigger_type=1,
                       script_name='pre_withdraw',
                       after_script_name='post_withdraw',
                       actbox_name='withdraw',
                       actbox_url='',
                       actbox_category='workflow',
                       props={'guard_roles': 'Owner'},
                       )

    # State Variable
    wf.variables.setStateVar('review_state')

    # Variable Initialization
    vdef = wf.variables['action']
    vdef.setProperties(description='The last transition',
                       default_value='',
                       default_expr='transition/getId|nothing',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['actor']
    vdef.setProperties(description='The ID of the user who performed the last transition',
                       default_value='',
                       default_expr='user/getId',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['comments']
    vdef.setProperties(description='Comments about the last transition',
                       default_value='',
                       default_expr="python:state_change.kwargs.get('comment','')",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['review_history']
    vdef.setProperties(description='Provides access to workflow history',
                       default_value='',
                       default_expr='state_change/getHistory',
                       for_catalog=0,
                       for_status=0,
                       update_always=0,
                       props={'guard_permissions': 'Request review; Review portal content; View'})

    vdef = wf.variables['time']
    vdef.setProperties(description='Time of the last transition',
                       default_value='',
                       default_expr='state_change/getDateTime',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    # Worklist Initialization
    ldef = wf.worklists['uwosh_oie_worklist_archived']
    ldef.setProperties(description='',
                       actbox_name='archived (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=archived',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'archived'})

    ldef = wf.worklists['uwosh_oie_worklist_conditionallyadmitted']
    ldef.setProperties(description='',
                       actbox_name='conditionallyAdmitted (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=conditionallyAdmitted',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'conditionallyAdmitted'})

    ldef = wf.worklists['uwosh_oie_worklist_deadlinemanagement']
    ldef.setProperties(description='',
                       actbox_name='',
                       actbox_url='',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'deadlineManagement'})

    ldef = wf.worklists['uwosh_oie_worklist_declined']
    ldef.setProperties(description='',
                       actbox_name='declined (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=declined',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'declined'})

    ldef = wf.worklists['uwosh_oie_worklist_facapprovedneedsprogrammanagerreview']
    ldef.setProperties(description='',
                       actbox_name='facApprovedNeedsProgramManagerReview (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=facApprovedNeedsProgramManagerReview',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'facApprovedNeedsProgramManagerReview'})

    ldef = wf.worklists['uwosh_oie_worklist_facultyreview']
    ldef.setProperties(description='',
                       actbox_name='facultyReview (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=facultyReview',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'facultyReview'})

    ldef = wf.worklists['uwosh_oie_worklist_faheldincomplete']
    ldef.setProperties(description='',
                       actbox_name='FAHeldIncomplete (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=FAHeldIncomplete',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'FAHeldIncomplete'})

    ldef = wf.worklists['uwosh_oie_worklist_incomplete']
    ldef.setProperties(description='',
                       actbox_name='incomplete (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=incomplete',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'incomplete'})

    ldef = wf.worklists['uwosh_oie_worklist_needsdirectorreview']
    ldef.setProperties(description='',
                       actbox_name='',
                       actbox_url='',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'needsDirectorReview'})

    ldef = wf.worklists['uwosh_oie_worklist_needsprogrammanagerreview']
    ldef.setProperties(description='',
                       actbox_name='',
                       actbox_url='',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'needsProgramManagerReview'})

    ldef = wf.worklists['uwosh_oie_worklist_private']
    ldef.setProperties(description='',
                       actbox_name='private (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=private',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'private'})

    ldef = wf.worklists['uwosh_oie_worklist_readyforconditionaladmit']
    ldef.setProperties(description='',
                       actbox_name='',
                       actbox_url='',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'readyForConditionalAdmit'})

    ldef = wf.worklists['uwosh_oie_worklist_seatassigned']
    ldef.setProperties(description='',
                       actbox_name='',
                       actbox_url='',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'seatAssigned'})

    ldef = wf.worklists['uwosh_oie_worklist_waitingforprintmaterials']
    ldef.setProperties(description='',
                       actbox_name='waitingForPrintMaterials (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=waitingForPrintMaterials',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'waitingForPrintMaterials'})

    ldef = wf.worklists['uwosh_oie_worklist_waitlist']
    ldef.setProperties(description='',
                       actbox_name='waitlist (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=waitlist',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'waitlist'})

    ldef = wf.worklists['uwosh_oie_worklist_withdrawn']
    ldef.setProperties(description='',
                       actbox_name='withdrawn (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=withdrawn',
                       actbox_category='global',
                       props={'guard_permissions': 'UWOshOIE: Review OIE Application',
                              'var_match_review_state': 'withdrawn'})

    # Script Initialization
    wf.scripts._setObject('attempt_transition_to_FAHeld',
                          ExternalMethod('attempt_transition_to_FAHeld', 'attempt_transition_to_FAHeld',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'attempt_transition_to_FAHeld'))
    
    wf.scripts._setObject('post_addComment',
                          ExternalMethod('post_addComment', 'post_addComment',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_addComment'))
    
    wf.scripts._setObject('post_addToWaitlist',
                          ExternalMethod('post_addToWaitlist', 'post_addToWaitlist',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_addToWaitlist'))
    
    wf.scripts._setObject('post_admitConditionally',
                          ExternalMethod('post_admitConditionally', 'post_admitConditionally',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_admitConditionally'))
    
    wf.scripts._setObject('post_approveForFA',
                          ExternalMethod('post_approveForFA', 'post_approveForFA',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_approveForFA'))
    
    wf.scripts._setObject('post_archive',
                          ExternalMethod('post_archive', 'post_archive',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_archive'))
    
    wf.scripts._setObject('post_assertReadyForConditionalAdmit',
                          ExternalMethod('post_assertReadyForConditionalAdmit', 'post_assertReadyForConditionalAdmit',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_assertReadyForConditionalAdmit'))
    
    wf.scripts._setObject('post_assignSeat',
                          ExternalMethod('post_assignSeat', 'post_assignSeat',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_assignSeat'))
    
    wf.scripts._setObject('post_decline',
                          ExternalMethod('post_decline', 'post_decline',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_decline'))
    
    wf.scripts._setObject('post_declineFromFacultyReview',
                          ExternalMethod('post_declineFromFacultyReview', 'post_declineFromFacultyReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_declineFromFacultyReview'))
    
    wf.scripts._setObject('post_facultyApproves',
                          ExternalMethod('post_facultyApproves', 'post_facultyApproves',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_facultyApproves'))
    
    wf.scripts._setObject('post_holdForFAIncomplete',
                          ExternalMethod('post_holdForFAIncomplete', 'post_holdForFAIncomplete',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_holdForFAIncomplete'))
    
    wf.scripts._setObject('post_manageDeadlines',
                          ExternalMethod('post_manageDeadlines', 'post_manageDeadlines',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_manageDeadlines'))
    
    wf.scripts._setObject('post_recheckForFAHold',
                          ExternalMethod('post_recheckForFAHold', 'post_recheckForFAHold',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_recheckForFAHold'))
    
    wf.scripts._setObject('post_sendForDirectorReview',
                          ExternalMethod('post_sendForDirectorReview', 'post_sendForDirectorReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_sendForDirectorReview'))
    
    wf.scripts._setObject('post_sendForFacultyReview',
                          ExternalMethod('post_sendForFacultyReview', 'post_sendForFacultyReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_sendForFacultyReview'))
    
    wf.scripts._setObject('post_sendForProgramManagerReview',
                          ExternalMethod('post_sendForProgramManagerReview', 'post_sendForProgramManagerReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_sendForProgramManagerReview'))
    
    wf.scripts._setObject('post_submit',
                          ExternalMethod('post_submit', 'post_submit',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_submit'))
    
    wf.scripts._setObject('post_waitForPrintedMaterials',
                          ExternalMethod('post_waitForPrintedMaterials', 'post_waitForPrintedMaterials',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_waitForPrintedMaterials'))
    
    wf.scripts._setObject('post_withdraw',
                          ExternalMethod('post_withdraw', 'post_withdraw',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'post_withdraw'))
    
    wf.scripts._setObject('pre_addComment',
                          ExternalMethod('pre_addComment', 'pre_addComment',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_addComment'))
    
    wf.scripts._setObject('pre_addToWaitlist',
                          ExternalMethod('pre_addToWaitlist', 'pre_addToWaitlist',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_addToWaitlist'))
    
    wf.scripts._setObject('pre_admitConditionally',
                          ExternalMethod('pre_admitConditionally', 'pre_admitConditionally',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_admitConditionally'))
    
    wf.scripts._setObject('pre_approveForFA',
                          ExternalMethod('pre_approveForFA', 'pre_approveForFA',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_approveForFA'))
    
    wf.scripts._setObject('pre_archive',
                          ExternalMethod('pre_archive', 'pre_archive',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_archive'))
    
    wf.scripts._setObject('pre_assertReadyForConditionalAdmit',
                          ExternalMethod('pre_assertReadyForConditionalAdmit', 'pre_assertReadyForConditionalAdmit',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_assertReadyForConditionalAdmit'))
    
    wf.scripts._setObject('pre_assignSeat',
                          ExternalMethod('pre_assignSeat', 'pre_assignSeat',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_assignSeat'))
    
    wf.scripts._setObject('pre_decline',
                          ExternalMethod('pre_decline', 'pre_decline',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_decline'))
    
    wf.scripts._setObject('pre_declineFromFacultyReview',
                          ExternalMethod('pre_declineFromFacultyReview', 'pre_declineFromFacultyReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_declineFromFacultyReview'))
    
    wf.scripts._setObject('pre_facultyApproves',
                          ExternalMethod('pre_facultyApproves', 'pre_facultyApproves',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_facultyApproves'))
    
    wf.scripts._setObject('pre_holdForFAIncomplete',
                          ExternalMethod('pre_holdForFAIncomplete', 'pre_holdForFAIncomplete',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_holdForFAIncomplete'))
    
    wf.scripts._setObject('pre_manageDeadlines',
                          ExternalMethod('pre_manageDeadlines', 'pre_manageDeadlines',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_manageDeadlines'))
    
    wf.scripts._setObject('pre_recheckForFAHold',
                          ExternalMethod('pre_recheckForFAHold', 'pre_recheckForFAHold',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_recheckForFAHold'))
    
    wf.scripts._setObject('pre_sendForDirectorReview',
                          ExternalMethod('pre_sendForDirectorReview', 'pre_sendForDirectorReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_sendForDirectorReview'))
    
    wf.scripts._setObject('pre_sendForFacultyReview',
                          ExternalMethod('pre_sendForFacultyReview', 'pre_sendForFacultyReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_sendForFacultyReview'))
    
    wf.scripts._setObject('pre_sendForProgramManagerReview',
                          ExternalMethod('pre_sendForProgramManagerReview', 'pre_sendForProgramManagerReview',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_sendForProgramManagerReview'))
    
    wf.scripts._setObject('pre_submit',
                          ExternalMethod('pre_submit', 'pre_submit',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_submit'))
    
    wf.scripts._setObject('pre_waitForPrintedMaterials',
                          ExternalMethod('pre_waitForPrintedMaterials', 'pre_waitForPrintedMaterials',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_waitForPrintedMaterials'))
    
    wf.scripts._setObject('pre_withdraw',
                          ExternalMethod('pre_withdraw', 'pre_withdraw',
                                         'UWOshOIE.OIEStudentApplicationWorkflow_scripts', 'pre_withdraw'))
    
def create_OIEStudentApplicationWorkflow(id):
    """Create, setup and return the workflow.
    """
    ob = DCWorkflowDefinition(id)
    setup_OIEStudentApplicationWorkflow(ob)
    return ob

addWorkflowFactory(create_OIEStudentApplicationWorkflow,
                   id='OIEStudentApplicationWorkflow',
                   title='OIEStudentApplicationWorkflow')
