#
# Generated by dumpDCWorkflow.py written by Sebastien Bigaret
# Original workflow id/title: UWOshOIEProgramWorkflow/UWOshOIE Program Workflow
# Date: 2008/04/08 09:53:04.621 GMT-5
#
# WARNING: this dumps does NOT contain any scripts you might have added to
# the workflow, IT IS YOUR RESPONSABILITY TO MAKE BACKUPS FOR THESE SCRIPTS.
#
# No script detected in this workflow
#
"""
Programmatically create a workflow type.
"""
__version__ = "$Id: dumpDCWorkflow.py 25723 2006-07-04 08:41:22Z b_mathieu $"

from Products.CMFCore.WorkflowTool import addWorkflowFactory
from Products.DCWorkflow.DCWorkflow import DCWorkflowDefinition
from Products.PythonScripts.PythonScript import PythonScript
from Products.ExternalMethod.ExternalMethod import ExternalMethod

def setup_UWOshOIEProgramWorkflow(wf):
    """Setup the workflow
    """
    wf.setProperties(title='UWOshOIE Program Workflow')

    for s in ('Created',):
        wf.states.addState(s)
    for t in ():
        wf.transitions.addTransition(t)
    for v in ('action', 'actor', 'comments', 'review_history', 'time'):
        wf.variables.addVariable(v)
    for l in ('program_list',):
        wf.worklists.addWorklist(l)
    for p in ('Access contents information',
              'Modify portal content',
              'View',
              'UWOshOIE: Modify Office Use Only fields',
              'list',
              'Add portal content'):
        wf.addManagedPermission(p)

    # Initial State
    wf.states.setInitialState('Created')

    # State Initialization
    sdef = wf.states['Created']
    sdef.setProperties(title='State it will always be in',
                       description='',
                       transitions=())
    sdef.setPermission('list', 0,
                      ['Owner',
                      'Authenticated',
                      'Member',
                      'UWOshOIEDirector',
                      'UWOshOIEFacReview',
                      'UWOshOIEFinAid',
                      'UWOshOIEFrontLineAdvisor',
                      'UWOshOIEProgramManager'])
    sdef.setPermission('Modify portal content', 0,
                      ['Owner',
                      'UWOshOIEDirector',
                      'UWOshOIEFrontLineAdvisor',
                      'UWOshOIEProgramManager'])
    sdef.setPermission('Add portal content', 0,
                    ['Owner',
                    'UWOshOIEDirector',
                    'UWOshOIEFrontLineAdvisor',
                    'UWOshOIEProgramManager'])
    sdef.setPermission('View', 0,
                      ['Owner',
                      'Authenticated',
                      'Member',
                      'UWOshOIEDirector',
                      'UWOshOIEFacReview',
                      'UWOshOIEFinAid',
                      'UWOshOIEFrontLineAdvisor',
                      'UWOshOIEProgramManager'])
    sdef.setPermission('Access contents information', 0,
                      ['Owner',
                      'Authenticated',
                      'Member',
                      'UWOshOIEDirector',
                      'UWOshOIEFacReview',
                      'UWOshOIEFinAid',
                      'UWOshOIEFrontLineAdvisor',
                      'UWOshOIEProgramManager'])
    sdef.setPermission('UWOshOIE: Modify Office Use Only fields', 0,
                      ['UWOshOIEDirector', 'UWOshOIEFrontLineAdvisor', 'UWOshOIEProgramManager'])

    # Transition Initialization
    # State Variable
    wf.variables.setStateVar('review_state')

    # Variable Initialization
    vdef = wf.variables['action']
    vdef.setProperties(description='The last transition',
                       default_value='',
                       default_expr='transition/getId|nothing',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['actor']
    vdef.setProperties(description='The ID of the user who performed the last transition',
                       default_value='',
                       default_expr='user/getId',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['comments']
    vdef.setProperties(description='Comments about the last transition',
                       default_value='',
                       default_expr="python:state_change.kwargs.get('comment', '')",
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    vdef = wf.variables['review_history']
    vdef.setProperties(description='Provides access to workflow history',
                       default_value='',
                       default_expr='state_change/getHistory',
                       for_catalog=0,
                       for_status=0,
                       update_always=0,
                       props={'guard_permissions': 'Request review; Review portal content'})

    vdef = wf.variables['time']
    vdef.setProperties(description='Time of the last transition',
                       default_value='',
                       default_expr='state_change/getDateTime',
                       for_catalog=0,
                       for_status=1,
                       update_always=1,
                       props=None)

    # Worklist Initialization
    ldef = wf.worklists['program_list']
    ldef.setProperties(description='List of programs',
                       actbox_name='Count (%(count)d)',
                       actbox_url='%(portal_url)s/search?review_state=pending',
                       actbox_category='global',
                       props={'guard_permissions': 'Review portal content',
                              'var_match_review_state': 'pending'})

def create_UWOshOIEProgramWorkflow(id):
    """Create, setup and return the workflow.
    """
    ob = DCWorkflowDefinition(id)
    setup_UWOshOIEProgramWorkflow(ob)
    return ob

addWorkflowFactory(create_UWOshOIEProgramWorkflow,
                   id='UWOshOIEProgramWorkflow',
                   title='UWOshOIE Program Workflow')
