Vocabularies = {}

Vocabularies['UWOshOIEDayOfMonth'] = (
    ('-- choose one --', u'-- choose one --'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('31', '31'),
)

Vocabularies['UWOshOIESessionHours'] = (
    ('9am - 1pm', u'9am - 1pm'),
    ('3pm - 5pm', u'3pm - 5pm'),
)

Vocabularies['UWOshOIESubjects'] = (
    ('-- choose one --', u'-- choose one --'),
    ('AF AM ST', u'AF AM ST'),
    ('ANTHRO', u'ANTHRO'),
    ('ARABIC', u'ARABIC'),
    ('ARAPAHO', u'ARAPAHO'),
    ('ART', u'ART'),
    ('ASTRONY', u'ASTRONY'),
    ('BIOLOGY', u'BIOLOGY'),
    ('BUSINESS', u'BUSINESS'),
    ('CHEM', u'CHEM'),
    ('CNSLR ED', u'CNSLR ED'),
    ('COMM', u'COMM'),
    ('COMP SCI', u'COMP SCI'),
    ('CRIM JUS', u'CRIM JUS'),
    ('DFLL', u'DFLL'),
    ('ECON', u'ECON'),
    ('ED FOUND', u'ED FOUND'),
    ('ED LDRSP', u'ED LDRSP'),
    ('ELEM ED', u'ELEM ED'),
    ('ENGLISH', u'ENGLISH'),
    ('ENV STDS', u'ENV STDS'),
    ('EXT STDS', u'EXT STDS'),
    ('FL ELECT', u'FL ELECT'),
    ('FR ABRD', u'FR ABRD'),
    ('FRENCH', u'FRENCH'),
    ('GEN ELEC', u'GEN ELEC'),
    ('GEN STDS', u'GEN STDS'),
    ('GEOG', u'GEOG'),
    ('GEOLOGY', u'GEOLOGY'),
    ('GERMAN', u'GERMAN'),
    ('HEALTH', u'HEALTH'),
    ('HISTORY', u'HISTORY'),
    ('HU ELECT', u'HU ELECT'),
    ('HUMAN SV', u'HUMAN SV'),
    ('INTRDSCP', u'INTRDSCP'),
    ('INTRNTL', u'INTRNTL'),
    ('JAPANESE', u'JAPANESE'),
    ('JOURNAL', u'JOURNAL'),
    ('KINESIOL', u'KINESIOL'),
    ('LIB SCI', u'LIB SCI'),
    ('LIB STDS', u'LIB STDS'),
    ('MATH', u'MATH'),
    ('MED TECH', u'MED TECH'),
    ('MIL SCI', u'MIL SCI'),
    ('MPA', u'MPA'),
    ('MUSIC', u'MUSIC'),
    ('NS ELECT', u'NS ELECT'),
    ('NURS-ACC', u'NURS-ACC'),
    ('NURS-CNP', u'NURS-CNP'),
    ('NURSING', u'NURSING'),
    ('PBIS', u'PBIS'),
    ('PHIL', u'PHIL'),
    ('PHYS SCI', u'PHYS SCI'),
    ('PHYS AST', u'PHYS AST'),
    ('POLI SCI', u'POLI SCI'),
    ('PRAC ART', u'PRAC ART'),
    ('PRTGUESE', u'PRTGUESE'),
    ('PSYCH', u'PSYCH'),
    ('PUB ADM', u'PUB ADM'),
    ('READING', u'READING'),
    ('RELSTDS', u'RELSTDS'),
    ('RUSSIAN', u'RUSSIAN'),
    ('SEC ED', u'SEC ED'),
    ('SHOSHONE', u'SHOSHONE'),
    ('SOC', u'SOC'),
    ('SOC WORK', u'SOC WORK'),
    ('SPANISH', u'SPANISH'),
    ('SPEC ED', u'SPEC ED'),
    ('SRVC CRS', u'SRVC CRS'),
    ('SS ELECT', u'SS ELECT'),
    ('TBIS', u'TBIS'),
    ('THEATRE', u'THEATRE'),
    ('URB REG', u'URB REG'),
    ('WOM STDS', u'WOM STDS'),
)

Vocabularies['UWOshOIEMonths'] = (
    ('-- choose one --', u'-- choose one --'),
    ('January', u'January'),
    ('February', u'February'),
    ('March', u'March'),
    ('April', u'April'),
    ('May', u'May'),
    ('June', u'June'),
    ('July', u'July'),
    ('August', u'August'),
    ('September', u'September'),
    ('October', u'October'),
    ('November', u'November'),
    ('December', u'December'),
)

Vocabularies['UWOshOIEGraduationMonths'] = (
    ('-- choose one --', u'-- choose one --'),
    ('Not a Student', u'Not a Student'),
    ('May', u'May'),
    ('August', u'August'),
    ('December', u'December'),
)

Vocabularies['UWOshOIEMajors'] = (
    ('-- choose one --', u'-- choose one --'),
    ('Accounting', u'Accounting'),
    ('African American Studies', u'African American Studies'),
    ('Anthropology', u'Anthropology'),
    ('Art', u'Art'),
    ('Biology', u'Biology'),
    ('Broadfield Natural Science', u'Broadfield Natural Science'),
    ('Broadfield Social Science', u'Broadfield Social Science'),
    ('Canada and U.S. Studies', u'Canada and U.S. Studies'),
    ('Chemistry', u'Chemistry'),
    ('Communication', u'Communication'),
    ('Computer Science', u'Computer Science'),
    ('Criminal Justice', u'Criminal Justice'),
    ('Dual Early Childhood PK-3 and Special Education Birth through Age 8', u'Dual Early Childhood PK-3 and Special Education Birth through Age 8'),
    ('Dual Elementary 1-6 and Special', u'Dual Elementary 1-6 and Special'),
    ('Earth Science', u'Earth Science'),
    ('Economics', u'Economics'),
    ('Economics', u'Economics'),
    ('Education', u'Education'),
    ('Elementary Education', u'Elementary Education'),
    ('English', u'English'),
    ('English as a Second Language', u'English as a Second Language'),
    ('Environmental Studies', u'Environmental Studies'),
    ('Finance', u'Finance'),
    ('Fine Arts', u'Fine Arts'),
    ('French', u'French'),
    ('Geography', u'Geography'),
    ('Geology', u'Geology'),
    ('German', u'German'),
    ('History', u'History'),
    ('Human Resources', u'Human Resources'),
    ('Human Services', u'Human Services'),
    ('Individually Planned', u'Individually Planned'),
    ('Interdisciplinary Studies', u'Interdisciplinary Studies'),
    ('International Studies', u'International Studies'),
    ('Journalism', u'Journalism'),
    ('Liberal Arts', u'Liberal Arts'),
    ('Liberal Studies', u'Liberal Studies'),
    ('Management Information Systems (MIS)', u'Management Information Systems (MIS)'),
    ('Marketing', u'Marketing'),
    ('Mathematics', u'Mathematics'),
    ('Medical Technology', u'Medical Technology'),
    ('Microbiology', u'Microbiology'),
    ('Military Science', u'Military Science'),
    ('Music', u'Music'),
    ('Music Education', u'Music Education'),
    ('Music Therapy', u'Music Therapy'),
    ('Nursing', u'Nursing'),
    ('Operations Management', u'Operations Management'),
    ('Philosophy', u'Philosophy'),
    ('Physical Education', u'Physical Education'),
    ('Physics', u'Physics'),
    ('Political Science', u'Political Science'),
    ('Pre-Professional Studies', u'Pre-Professional Studies'),
    ('Psychology', u'Psychology'),
    ('Public Affairs', u'Public Affairs'),
    ('Radio TV Film (RTF)', u'Radio TV Film (RTF)'),
    ('Religious Studies', u'Religious Studies'),
    ('Secondary Education', u'Secondary Education'),
    ('Secondary Education', u'Secondary Education'),
    ('Social Work', u'Social Work'),
    ('Sociology', u'Sociology'),
    ('Spanish', u'Spanish'),
    ('Special Education Cross-Categorical', u'Special Education Cross-Categorical'),
    ('Urban and Regional Studies', u'Urban and Regional Studies'),
)